# Generated by Django 2.0.3 on 2018-03-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.IntegerField()),
                ('status', models.BooleanField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
