# Generated by Django 2.0.3 on 2018-03-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_devicecontrol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicecontrol',
            old_name='current_state',
            new_name='set_state',
        ),
    ]
